import {
	FaDribbble,
	FaFacebook,
	FaLinkedin,
	FaMailBulk,
	FaMapMarked,
	FaMobileAlt,
	FaTwitter,
} from "react-icons/fa";

export const Navigations = [
	{
		id: 0,
		name: "Home",
		url: "/",
	},
	{
		id: 1,
		name: "Battles",
		url: "battles",
	},
	{
		id: 2,
		name: "Add Battle",
		url: "https://docs.google.com/forms/d/e/1FAIpQLSfY_zPo-FXo3ZEyoFf_TXkb1pWcNkEwR8bMcJJ-hlZHovKPuw/viewform",
	},
	{
		id: 3,
		name: "About",
		url: "about",
	},
	{
		id: 4,
		name: "Contact",
		url: "contact",
	},
];

export const EventList = [
	{
		id: 1,
		date: 2023 - 11 - 26,
		name: "Locking japan Crew battle(hyper link to Detail Page1)",
		location: "Tyokyo, japan",
		Genre: "Locking",
		Format: "Crew battle",
		country: "myCountry",
		city: "myCity",
		registration_period: "2022 to 2023",
		website: "url",
		description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis, eaque accusantium. Laudantium repudiandae, ex distinctio ipsam, odio molestiae quae tempore eveniet non accusamus tenetur cumque, aliquam reiciendis consequatur maiores dignissimos?`,
	},
	{
		id: 2,
		date: 2023 - 11 - 25,
		name: "Break seoul 1 on 1 (hyper link to detail page1)",
		location: "Seoul, Korea",
		Genre: "Breaking",
		Format: "1 vs 1",
		country: "myCountry",
		city: "myCity",
		registration_period: "2022 to 2023",
		website: "url",
		description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis, eaque accusantium. Laudantium repudiandae, ex distinctio ipsam, odio molestiae quae tempore eveniet non accusamus tenetur cumque, aliquam reiciendis consequatur maiores dignissimos?`,
	},
	{
		id: 3,
		date: 2023 - 11 - 26,
		name: "Locking japan Crew battle(hyper link to Detail Page2)",
		location: "Tyokyo, japan",
		Genre: "Locking",
		Format: "Crew battle",
		country: "myCountry",
		city: "myCity",
		registration_period: "2022 to 2023",
		website: "url",
		description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis, eaque accusantium. Laudantium repudiandae, ex distinctio ipsam, odio molestiae quae tempore eveniet non accusamus tenetur cumque, aliquam reiciendis consequatur maiores dignissimos?`,
	},
	{
		id: 4,
		date: 2023 - 11 - 25,
		name: "Break seoul 1 on 1 (hyper link to detail page2)",
		location: "Seoul, Korea",
		Genre: "Breaking",
		Format: "1 vs 1",
		country: "myCountry",
		city: "myCity",
		registration_period: "2022 to 2023",
		website: "url",
		description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis, eaque accusantium. Laudantium repudiandae, ex distinctio ipsam, odio molestiae quae tempore eveniet non accusamus tenetur cumque, aliquam reiciendis consequatur maiores dignissimos?`,
	},
	{
		id: 5,
		date: 2023 - 11 - 26,
		name: "Locking japan Crew battle(hyper link to Detail Page3)",
		location: "Tyokyo, japan",
		Genre: "Locking",
		Format: "Crew battle",
		country: "myCountry",
		city: "myCity",
		registration_period: "2022 to 2023",
		website: "url",
		description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis, eaque accusantium. Laudantium repudiandae, ex distinctio ipsam, odio molestiae quae tempore eveniet non accusamus tenetur cumque, aliquam reiciendis consequatur maiores dignissimos?`,
	},
	{
		id: 6,
		date: 2023 - 11 - 26,
		name: "Locking japan Crew battle(hyper link to Detail Page3)",
		location: "Tyokyo, japan",
		Genre: "Locking",
		Format: "Crew battle",
		country: "myCountry",
		city: "myCity",
		registration_period: "2022 to 2023",
		website: "url",
		description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis, eaque accusantium. Laudantium repudiandae, ex distinctio ipsam, odio molestiae quae tempore eveniet non accusamus tenetur cumque, aliquam reiciendis consequatur maiores dignissimos?`,
	},
	{
		id: 7,
		date: 2023 - 11 - 25,
		name: "Break seoul 1 on 1 (hyper link to detail page4)",
		location: "Seoul, Korea",
		Genre: "Breaking",
		Format: "1 vs 1",
		country: "myCountry",
		city: "myCity",
		registration_period: "2022 to 2023",
		website: "url",
		description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis, eaque accusantium. Laudantium repudiandae, ex distinctio ipsam, odio molestiae quae tempore eveniet non accusamus tenetur cumque, aliquam reiciendis consequatur maiores dignissimos?`,
	},
	{
		id: 8,
		date: 2023 - 11 - 26,
		name: "Locking japan Crew battle(hyper link to Detail Page4)",
		location: "Tyokyo, japan",
		Genre: "Locking",
		Format: "Crew battle",
		country: "myCountry",
		city: "myCity",
		registration_period: "2022 to 2023",
		website: "url",
		description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis, eaque accusantium. Laudantium repudiandae, ex distinctio ipsam, odio molestiae quae tempore eveniet non accusamus tenetur cumque, aliquam reiciendis consequatur maiores dignissimos?`,
	},
	{
		id: 9,
		date: 2023 - 11 - 26,
		name: "Locking japan Crew battle(hyper link to Detail Page5)",
		location: "Tyokyo, japan",
		Genre: "Locking",
		Format: "Crew battle",
		country: "myCountry",
		city: "myCity",
		registration_period: "2022 to 2023",
		website: "url",
		description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis, eaque accusantium. Laudantium repudiandae, ex distinctio ipsam, odio molestiae quae tempore eveniet non accusamus tenetur cumque, aliquam reiciendis consequatur maiores dignissimos?`,
	},
	{
		id: 10,
		date: 2023 - 11 - 25,
		name: "Break seoul 1 on 1 (hyper link to detail page5)",
		location: "Seoul, Korea",
		Genre: "Breaking",
		Format: "1 vs 1",
		country: "myCountry",
		city: "myCity",
		registration_period: "2022 to 2023",
		website: "url",
		description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis, eaque accusantium. Laudantium repudiandae, ex distinctio ipsam, odio molestiae quae tempore eveniet non accusamus tenetur cumque, aliquam reiciendis consequatur maiores dignissimos?`,
	},
	{
		id: 11,
		date: 2023 - 11 - 26,
		name: "Locking japan Crew battle(hyper link to Detail Page6)",
		location: "Tyokyo, japan",
		Genre: "Locking",
		Format: "Crew battle",
		country: "myCountry",
		city: "myCity",
		registration_period: "2022 to 2023",
		website: "url",
		description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis, eaque accusantium. Laudantium repudiandae, ex distinctio ipsam, odio molestiae quae tempore eveniet non accusamus tenetur cumque, aliquam reiciendis consequatur maiores dignissimos?`,
	},
];

export const socialIcons = [
	{
		id: 0,
		icon: FaDribbble,
		link: "https://twitter.com/SamsonChiemezie",
	},
	{
		id: 1,
		icon: FaFacebook,
		link: "https://twitter.com/SamsonChiemezie",
	},
	{
		id: 2,
		icon: FaLinkedin,
		link: "https://twitter.com/SamsonChiemezie",
	},
	{
		id: 3,
		icon: FaTwitter,
		link: "https://twitter.com/SamsonChiemezie",
	},
];

export const contactObj = [
	{
		id: 1,
		icon: FaMobileAlt,
		title: "Call Us On",
		text: "+86-123453435346",
	},
	{
		id: 2,
		icon: FaMailBulk,
		title: "Email Us At",
		text: "YourEmail@gmail.com",
	},
	{
		id: 3,
		icon: FaMapMarked,
		title: "Visit Office",
		text: "No.adrress",
	},
];
